version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    networks:
      - app_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    networks:
      - app_network
    depends_on:
      - postgres
    ports:
      - '8080:8080'
networks:
  app_network:
    driver: bridge
volumes:
  postgres_volume:
    driver: local
